name: Deploy DApp to Testnet
on:
  push:
    branches: [staging]
jobs:
  deploy-testnet:
    uses: wpdas/alem/.github/workflows/deploy-testnet.yml@main
    with:
      signer-account-address: wendersonpires.testnet
      signer-public-key: ed25519:43XNk6CdzdtYzu67vjGzrCyXJ1N6jFwv3mSUkyFkP73H
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.TESTNET_SIGNER_PRIVATE_KEY }}