name: Deploy DApp to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: wpdas/alem/.github/workflows/deploy.yml@main
    with:
      signer-account-address: wendersonpires.near
      signer-public-key: ed25519:7T3RQbpsWpqmM8R6s7iwnnrywzCvRUXWQcifB9q4H26N
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}